# Generated by Django 4.2.3 on 2023-07-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('categoria', models.CharField(choices=[('Pastas', 'Pastas'), ('Pizzas', 'Pizzas'), ('Hamburguesas', 'Hamburguesas'), ('Ensaladas', 'Ensalada'), ('Empanadas', 'Empanadas'), ('Panchos', 'Panchos'), ('Bifes', 'Bifes'), ('Chorizos', 'Chorizos'), ('Milanesas', 'Milanesas')], max_length=100)),
            ],
        ),
    ]
